import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Card from "../components/card";

import coffeeStores from "../data/coffee-stores.json"

export default function Home () {
    const handleOnBannerButtonClick = () => {
        console.log('h1')
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shops</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerButtonClick } />
          <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400}/>
          </div>
          <div className={styles.cardLayout}>
              {coffeeStores.map((store) => {
                  return <Card
                      name={store.name}
                      imgUrl={store.imgUrl}
                      href={`/coffee-store/${store.id}`}
                      className={styles.card}
                  />
              })}

          </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
